//ADD ITEM TO CART
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"

// REMOVE ITEM FROM CART
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART"
// USER ITEM CLEAR 
export const REMOVE_ITEM_CLEAR = "REMOVE_ITEM_CLEAR"


// CART SAVE SHIPPING ADDRESS 
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS"

export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS"

